# Generated by Django 2.1.3 on 2018-11-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagen',
            new_name='img',
        ),
    ]
